hf_token: ENC[AES256_GCM,data:Rl0w8KX9h66OcF8sV5heSSLE84hvIq+sRLmFi5JqHomGhPv4Fg==,iv:ImAWPTSbA0M5SzNy+6HT3qwpgVu5a+3SUAsE8y88BQI=,tag:CcVAJgOVe+QIMxBMO0S+mw==,type:str]
anthropic_api_key: ""
groq_api_key: ""
sops:
    age:
        - recipient: age1g3q8la6ekarm8ynw0mq7chfpprfcrykn7atrefdm7s6ukg0v5arq60kmpt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqa1IrVjE3ZURkc3BjbUQ4
            Sk1QYlR1TUpsN0RDZzhhV042S3VSSVltdlJ3CnBCNEE5UkZNKy9HSThrTEY5RGcv
            TVdRWkljRUFCYlAzQ29oTDR3OEREMTgKLS0tIHk0UVcxR25aTTVoVktZK1ZtWHNE
            TEJZOU5KZk9YRDl5WWJkUEVFU3Z5OEkKGo5WA3S6z24GInuzFQ2hgMaESvVuBBjt
            jsXG6hvPgtIk0lnwPm/KfrDljkqLhkLynDaGlFlSPoVLcDbe2dJRNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:02:47Z"
    mac: ENC[AES256_GCM,data:/csDrKFLAF8T8B2Iw+YXBGKBk5whyjKL0/f/fezPKb7FOt7HGhW59olQyzLnRWyHfaVvPSTCBhrHpFaOAdjkxenAfauNHKrujHbCkqlSKysqPUVxXpmlkvLO+Y7snihWjrU5a0yE0yJcdyHJS5V7zAVSxZjSe7Fz28xlu7MaDJY=,iv:ex+aRAU+azgHNHL8PQ9HgfRbjg2UXs8RbyTF6O5p6so=,tag:2rJQyLC4uiEv1unisp0wdw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
