import type { PathwaySection, ActionData } from '../types/genomics'
import type { PGxEnzymeSection } from '../types/pgx'
import type { MortalityCause } from '../components/risk/RiskLandscape'
import type { SubstanceCard } from '../hooks/useAddictionData'
import type { ChecklistItem } from '../hooks/useChecklist'

// ── Print ────────────────────────────────────────────────────────────────────

export function printPage(mode: 'doctor' | 'prescriber' | 'pdf') {
  document.body.setAttribute('data-print-mode', mode)
  window.print()
  document.body.removeAttribute('data-print-mode')
}

// ── File download ────────────────────────────────────────────────────────────

export function downloadFile(content: string, filename: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().slice(0, 10)
}

function footer() {
  return `\n---\n_Generated by Genome Toolkit on ${today()}_\n`
}

// ── Mental Health Markdown ───────────────────────────────────────────────────

export function mentalHealthToMarkdown(
  sections: PathwaySection[],
  actions: Record<string, ActionData[]>,
): string {
  const lines: string[] = [
    `# Mental Health Genetic Profile`,
    `_Date: ${today()}_`,
    '',
  ]

  for (const section of sections) {
    lines.push(`## ${section.narrative.pathway}`)
    lines.push('')
    lines.push(section.narrative.body)
    lines.push('')

    if (section.genes.length > 0) {
      lines.push('| Gene | Variant | Genotype | Status | Evidence | Description |')
      lines.push('|------|---------|----------|--------|----------|-------------|')
      for (const g of section.genes) {
        lines.push(`| ${g.symbol} | ${g.variant} | ${g.genotype} | ${g.status} | ${g.evidenceTier} (${g.studyCount} sources) | ${g.description} |`)
      }
      lines.push('')
    }

    // Actions for genes in this section
    for (const gene of section.genes) {
      const geneActions = actions[gene.symbol]
      if (geneActions && geneActions.length > 0) {
        lines.push(`### Actions for ${gene.symbol}`)
        lines.push('')
        for (const a of geneActions) {
          const check = a.done ? '[x]' : '[ ]'
          lines.push(`- ${check} **${a.type.toUpperCase()}**: ${a.title}`)
          if (a.description) lines.push(`  ${a.description}`)
        }
        lines.push('')
      }
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── PGx Markdown ─────────────────────────────────────────────────────────────

export function pgxToMarkdown(sections: PGxEnzymeSection[]): string {
  const lines: string[] = [
    `# PGx / Drug Metabolism Report`,
    `_Date: ${today()}_`,
    '',
  ]

  for (const section of sections) {
    const e = section.enzyme
    lines.push(`## ${e.symbol} (${e.alleles}) -- ${e.status} metabolizer`)
    if (e.guideline) lines.push(`_Guideline: ${e.guideline}_`)
    lines.push('')
    lines.push(e.description)
    lines.push('')

    if (section.drugs.length > 0) {
      lines.push('| Drug Class | Category | Impact | Status | Notes |')
      lines.push('|-----------|----------|--------|--------|-------|')
      for (const d of section.drugs) {
        const danger = d.dangerNote ? ` **${d.dangerNote}**` : ''
        lines.push(`| ${d.drugClass} | ${d.category} | ${d.impact} | ${d.statusText} | ${d.description}${danger} |`)
      }
      lines.push('')
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Risk Landscape Markdown ──────────────────────────────────────────────────

export function riskLandscapeToMarkdown(causes: MortalityCause[]): string {
  const lines: string[] = [
    `# Mortality & Risk Landscape`,
    `_Date: ${today()}_`,
    '',
    '| Rank | Cause | % of Deaths | Status | Genes |',
    '|------|-------|------------|--------|-------|',
  ]

  for (const c of causes) {
    lines.push(`| ${c.rank} | ${c.cause} | ${c.pct}% | ${c.status} | ${c.genesText} |`)
  }
  lines.push('')

  // Expanded detail for causes with genes/actions
  for (const c of causes) {
    if (!c.genes?.length && !c.actions?.length) continue
    lines.push(`## ${c.rank}. ${c.cause}`)
    lines.push('')
    if (c.narrative) {
      lines.push(c.narrative)
      lines.push('')
    }
    if (c.genes && c.genes.length > 0) {
      lines.push('**Genes:**')
      for (const g of c.genes) {
        lines.push(`- **${g.symbol}** (${g.variant}) -- ${g.evidenceTier} -- ${g.status}: ${g.description}`)
      }
      lines.push('')
    }
    if (c.actions && c.actions.length > 0) {
      lines.push('**Actions:**')
      for (const a of c.actions) {
        lines.push(`- [ ] **${a.type.toUpperCase()}**: ${a.text}`)
      }
      lines.push('')
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Addiction Profile Markdown ────────────────────────────────────────────────

export function addictionToMarkdown(
  pathways: PathwaySection[],
  substances: SubstanceCard[],
): string {
  const lines: string[] = [
    `# Addiction & Reward Profile`,
    `_Date: ${today()}_`,
    '',
  ]

  for (const section of pathways) {
    lines.push(`## ${section.narrative.pathway}`)
    lines.push('')
    lines.push(section.narrative.body)
    lines.push('')

    if (section.genes.length > 0) {
      lines.push('| Gene | Variant | Genotype | Status | Evidence | Description |')
      lines.push('|------|---------|----------|--------|----------|-------------|')
      for (const g of section.genes) {
        lines.push(`| ${g.symbol} | ${g.variant} | ${g.genotype} | ${g.status} | ${g.evidenceTier} (${g.studyCount} sources) | ${g.description} |`)
      }
      lines.push('')
    }
  }

  if (substances.length > 0) {
    lines.push(`## Substance-Specific Harm Reduction`)
    lines.push('')
    for (const s of substances) {
      lines.push(`### ${s.name}`)
      lines.push(`_Status: ${s.status}_`)
      lines.push('')
      lines.push(s.description)
      lines.push('')
      lines.push(`**${s.harmTitle}:** ${s.harmText}`)
      lines.push('')
      lines.push(`_Genes: ${s.genes}_`)
      lines.push('')
    }
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Gene Detail Markdown ─────────────────────────────────────────────────────

export function geneToMarkdown(
  gene: { symbol: string; variant: string; rsid: string; genotype: string; status: string; evidenceTier: string; studyCount: number; description: string },
  actions: ActionData[],
): string {
  const lines: string[] = [
    `# Gene Report: ${gene.symbol}`,
    `_Date: ${today()}_`,
    '',
    `- **Variant:** ${gene.variant}`,
    `- **rsID:** ${gene.rsid}`,
    `- **Genotype:** ${gene.genotype}`,
    `- **Status:** ${gene.status}`,
    `- **Evidence:** ${gene.evidenceTier} (${gene.studyCount} sources)`,
    '',
    gene.description,
    '',
  ]

  if (actions.length > 0) {
    lines.push('## Actions')
    lines.push('')
    for (const a of actions) {
      const check = a.done ? '[x]' : '[ ]'
      lines.push(`- ${check} **${a.type.toUpperCase()}**: ${a.title}`)
      if (a.description) lines.push(`  ${a.description}`)
    }
    lines.push('')
  }

  lines.push(footer())
  return lines.join('\n')
}

// ── Checklist Markdown ───────────────────────────────────────────────────────

export function checklistToMarkdown(items: ChecklistItem[]): string {
  const lines: string[] = [
    `# Action Checklist`,
    `_Date: ${today()}_`,
    '',
  ]

  const pending = items.filter(i => !i.done)
  const done = items.filter(i => i.done)

  if (pending.length > 0) {
    lines.push('## Pending')
    lines.push('')
    for (const item of pending) {
      const gene = item.gene_symbol !== 'custom' ? ` (${item.gene_symbol})` : ''
      lines.push(`- [ ] ${item.title}${gene}`)
    }
    lines.push('')
  }

  if (done.length > 0) {
    lines.push('## Done')
    lines.push('')
    for (const item of done) {
      const gene = item.gene_symbol !== 'custom' ? ` (${item.gene_symbol})` : ''
      lines.push(`- [x] ${item.title}${gene}`)
    }
    lines.push('')
  }

  lines.push(footer())
  return lines.join('\n')
}
